[project]
name = "stream-response-with-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.44.0",
    "fastapi>=0.115.7",
    "uvicorn>=0.34.0",
]
